plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

include:
  - "**/*.md"

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    block: { line_numbers: true }
